# api_key_manager/schemas.py
from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional

# --- AgentUser Schemas ---
class AgentUserBase(BaseModel):
    username: str

class AgentUserCreate(AgentUserBase):
    password: str

class AgentUser(AgentUserBase):
    id: int
    is_active: bool
    created_at: datetime
    updated_at: Optional[datetime] = None

    class Config:
        orm_mode = True

# --- API Key Schemas ---
class ApiKeyBase(BaseModel):
    description: Optional[str] = None
    expires_at: Optional[datetime] = None

class ApiKeyCreate(ApiKeyBase):
    pass # No key needed here, it's generated by the backend

class ApiKeyResponse(ApiKeyBase):
    id: int
    key_prefix: str
    is_active: bool
    created_at: datetime
    last_used_at: Optional[datetime] = None

    class Config:
        orm_mode = True

class ApiKeyFullResponse(ApiKeyResponse):
    # This schema includes the plain_key, only returned upon generation
    plain_key: str = Field(..., description="The full API key, only shown once upon creation.")

class ApiKeyValidateRequest(BaseModel):
    api_key: str = Field(..., min_length=32, max_length=128) # Example length

class ApiKeyValidateResponse(BaseModel):
    is_valid: bool
    key_id: Optional[int] = None
    key_prefix: Optional[str] = None
    description: Optional[str] = None
    is_active: Optional[bool] = None
    expires_at: Optional[datetime] = None
    message: str = "Validation result"

# --- Authentication Schemas ---
class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    username: Optional[str] = None
