# amos-api-gateway/services/Dockerfile_service_a
FROM python:3.10-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["uvicorn", "service_a:app", "--host", "0.0.0.0", "--port", "8001"]
EXPOSE 8001
