const state={folder:'inbox',messages:[]};
const $=id=>document.getElementById(id);
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={detail:text||'Request failed'}}if(!r.ok)throw new Error(data.detail||'Request failed');return data}
function show(id,text,success=false){const el=$(id);el.textContent=text;el.className=success?'mail-message success':'mail-message'}
async function loadMailbox(){const data=await api('/api/v1/mail/me');if(!data.mailbox){$('mailbox-modal').classList.remove('hidden');$('mail-address').textContent='Create your @amos.com address';return}$('mail-address').textContent=data.mailbox.address;$('mailbox-modal').classList.add('hidden');await loadMessages()}
async function loadMessages(){state.messages=await api(`/api/v1/mail/messages?folder=${state.folder}`);$('folder-title').textContent=state.folder==='inbox'?'Inbox':'Sent';const list=$('mail-list');if(!state.messages.length){list.innerHTML='<p class="mail-empty">No messages yet.</p>';return}list.innerHTML=state.messages.map(m=>`<article class="mail-item ${m.is_read?'':'unread'}" data-id="${m.id}"><div class="meta"><span>${state.folder==='inbox'?m.sender_address:m.recipient_address}</span><span>${new Date(m.created_at).toLocaleString()}</span></div><div class="subject">${escapeHtml(m.subject)}</div></article>`).join('');document.querySelectorAll('.mail-item').forEach(el=>el.onclick=()=>openMessage(Number(el.dataset.id)))}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function openMessage(id){const m=state.messages.find(x=>x.id===id);if(!m)return;$('mail-reader').innerHTML=`<article class="mail-reader"><h2>${escapeHtml(m.subject)}</h2><div class="meta">From: ${escapeHtml(m.sender_address)}<br>To: ${escapeHtml(m.recipient_address)}<br>${new Date(m.created_at).toLocaleString()} · ${escapeHtml(m.delivery)} · ${escapeHtml(m.status)}</div><div class="body">${escapeHtml(m.body)}</div></article>`;if(state.folder==='inbox'&&!m.is_read){await api(`/api/v1/mail/messages/${id}/read`,{method:'POST'});m.is_read=1;loadMessages()}}
$('mailbox-form').addEventListener('submit',async e=>{e.preventDefault();try{const data=await api('/api/v1/mail/address',{method:'POST',body:JSON.stringify({username:$('mail-username').value})});show('mailbox-message',`Created ${data.address}`,true);await loadMailbox()}catch(err){show('mailbox-message',err.message)}});
$('mail-username').addEventListener('input',e=>$('username-preview').textContent=e.target.value.toLowerCase()||'username');
$('compose-button').onclick=()=>$('compose-modal').classList.remove('hidden');
$('close-compose').onclick=()=>$('compose-modal').classList.add('hidden');
$('compose-form').addEventListener('submit',async e=>{e.preventDefault();$('send-mail').disabled=true;try{const data=await api('/api/v1/mail/send',{method:'POST',body:JSON.stringify({to:$('compose-to').value,subject:$('compose-subject').value,body:$('compose-body').value})});show('compose-message',data.delivery==='internal'?'Delivered inside Amosclaud.':'Sent to the internet.',true);e.target.reset();await loadMessages();setTimeout(()=>$('compose-modal').classList.add('hidden'),700)}catch(err){show('compose-message',err.message)}finally{$('send-mail').disabled=false}});
document.querySelectorAll('.folder-button').forEach(b=>b.onclick=async()=>{state.folder=b.dataset.folder;document.querySelectorAll('.folder-button').forEach(x=>x.classList.toggle('active',x===b));await loadMessages()});
$('refresh-mail').onclick=loadMessages;
$('btn-logout').onclick=async()=>{await fetch('/api/v1/auth/logout',{method:'POST',credentials:'same-origin'});location.assign('/login')};
loadMailbox().catch(err=>{$('mail-list').innerHTML=`<p class="mail-empty">${escapeHtml(err.message)}</p>`});