const keyInput=document.getElementById('admin-key');const message=document.getElementById('message');const badge=document.getElementById('status-badge');const devices=document.getElementById('devices');
keyInput.value=sessionStorage.getItem('amosAdminKey')||'';
function show(text,ok=false){message.textContent=text;message.className=ok?'message ok':'message'}
function headers(){const key=keyInput.value.trim();if(!key)throw new Error('Enter the administrator key first.');return {'Content-Type':'application/json','X-Admin-Key':key}}
async function api(path,options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{...headers(),...(options.headers||{})}});const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch(_){data={detail:text}}if(!response.ok)throw new Error(data.detail||`Request failed (${response.status})`);return data}
async function loadStatus(){show('Checking access point…',true);try{const data=await api('/api/v1/admin/wifi/status');sessionStorage.setItem('amosAdminKey',keyInput.value.trim());badge.textContent='Online';badge.className='badge online';const identity=Array.isArray(data.identity)?data.identity[0]:data.identity||{};const resources=Array.isArray(data.resources)?data.resources[0]:data.resources||{};document.getElementById('identity').textContent=identity.name||identity.identity||'MikroTik';document.getElementById('platform').textContent=resources.platform||resources['board-name']||'RouterOS';document.getElementById('uptime').textContent=resources.uptime||'—';show('Access point connected.',true)}catch(error){badge.textContent='Offline';badge.className='badge offline';show(error.message)}}
async function loadDevices(){devices.textContent='Loading…';try{const data=await api('/api/v1/admin/wifi/devices');const rows=data.devices||[];if(!rows.length){devices.textContent='No connected devices found.';return}devices.innerHTML=rows.map(item=>`<div class="device"><strong>${escapeHtml(item['host-name']||item.comment||item.mac_address||item['mac-address']||'Unknown device')}</strong><div class="muted">${escapeHtml(item['mac-address']||item.mac_address||'')} ${escapeHtml(item.signal||item['signal-strength']||'')}</div></div>`).join('')}catch(error){devices.textContent=error.message}}
function escapeHtml(value){return String(value||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
document.getElementById('connect').addEventListener('click',async()=>{await loadStatus();if(badge.classList.contains('online'))await loadDevices()});document.getElementById('refresh').addEventListener('click',loadStatus);document.getElementById('refresh-devices').addEventListener('click',loadDevices);document.getElementById('forget').addEventListener('click',()=>{sessionStorage.removeItem('amosAdminKey');keyInput.value='';show('Administrator key removed.',true)});
document.getElementById('save-network').addEventListener('click',async()=>{const ssid=document.getElementById('ssid').value.trim();const password=document.getElementById('wifi-password').value;const disabled=document.getElementById('disabled').checked;if(!ssid){show('Enter a Wi-Fi network name.');return}if(password.length<8){show('Wi-Fi password must contain at least 8 characters.');return}show('Saving Wi-Fi settings…',true);try{await api('/api/v1/admin/wifi/network',{method:'PUT',body:JSON.stringify({ssid,password,disabled})});show('Wi-Fi settings saved. Connected devices may briefly disconnect.',true)}catch(error){show(error.message)}});
